<?php 
// Site content
$content = array(
		"title" => "Engagement Party",
		"lead" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut commodo, ipsum eu iaculis ornare, purus orci malesuada felis, ut eleifend nulla nisi dictum libero. Morbi fermentum nec ligula quis vestibulum. Quisque non diam ante. Suspendisse varius vehicula erat elementum convallis. Etiam mattis sed nunc quis suscipit. Donec eget ullamcorper magna, ut mattis quam. Nullam nec augue sit amet augue porta adipiscing. Suspendisse potenti. Sed vehicula consectetur aliquam. Cras condimentum magna vel dapibus rutrum.",
		"rsvp" => "Integer accumsan id magna rutrum sollicitudin. Aliquam tempus eros at nisi mollis, in pulvinar justo luctus. Phasellus lorem eros, congue et bibendum vel, semper eu nunc. Nam fringilla condimentum quam, ac tincidunt velit gravida non. Vivamus lacinia ornare velit porttitor mattis. Morbi at augue eu arcu iaculis commodo ac eleifend libero. Vestibulum lorem libero, tristique id arcu eget, molestie vulputate tellus.",
		"food" => "Mauris non lacinia nisl, id ullamcorper sapien. Nullam varius feugiat lectus, in porttitor magna malesuada a. Etiam porttitor augue et suscipit ornare. Curabitur felis dui, gravida faucibus orci bibendum, lobortis fermentum orci. In hac habitasse platea dictumst. Sed mauris tortor, fringilla sollicitudin quam eget, sodales blandit velit. Curabitur tempor erat mauris, sed faucibus ligula vestibulum a. Aliquam iaculis lacus erat, sit amet egestas sapien venenatis sit amet. Curabitur suscipit, lorem vel egestas condimentum, arcu nisi tincidunt lorem, sed feugiat nunc diam et metus. Aenean elit neque, blandit id gravida eget, congue non augue.",
		"venue" => "Sed est eros, pellentesque nec magna a, pretium rhoncus risus. Curabitur vitae nulla gravida, aliquam nulla quis, vestibulum nunc. Morbi vehicula eros ligula, in pulvinar tortor consequat ullamcorper. Etiam eget augue risus. Suspendisse feugiat eget tellus et luctus. Quisque vitae eros quis mi elementum accumsan. Cras posuere hendrerit enim quis dictum. Praesent porttitor neque purus. Proin ac fringilla ligula, in elementum erat. Aliquam venenatis dignissim feugiat. Nulla ultricies ante iaculis, pellentesque nunc nec, ultricies odio.",
		"contact" => "Quisque gravida magna eu rhoncus fringilla. Duis porta orci nec rhoncus semper. Quisque at diam vel quam convallis pretium ut ut nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Curabitur in ultricies ipsum. Phasellus rhoncus dui neque, ut molestie nibh mattis vitae. Nulla eget rutrum turpis. Aliquam pretium, lacus vitae sollicitudin semper, velit felis vulputate urna, sit amet blandit augue nunc id risus. Nam non ligula nunc. Nullam quis odio id tellus dictum lacinia. Duis sit amet lacus ultricies lorem tempus vehicula consequat eu leo.",
		"map-text" => "Duis semper, arcu nec vestibulum malesuada, turpis eros pellentesque risus, sit amet vehicula turpis tortor at mauris.",
		/* Click link -> embed on Google maps to get these */
		"map-src" => "https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Melbourne,+Victoria,+Australia&amp;aq=0&amp;oq=melbourne,+aust&amp;sll=37.0625,-95.677068&amp;sspn=62.226996,134.472656&amp;ie=UTF8&amp;hq=&amp;hnear=Melbourne+Victoria,+Australia&amp;t=m&amp;z=10&amp;ll=-37.814107,144.96328&amp;output=embed",
		"map-link" =>  "https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Melbourne,+Victoria,+Australia&amp;aq=0&amp;oq=melbourne,+aust&amp;sll=37.0625,-95.677068&amp;sspn=62.226996,134.472656&amp;ie=UTF8&amp;hq=&amp;hnear=Melbourne+Victoria,+Australia&amp;t=m&amp;z=10&amp;ll=-37.814107,144.96328",
		"footer" => "Footer here");
?>
